### ISSUE TITLE
Add Site in Firefox is Broken

### ISSUE THREAD

**Issue by hparadiz** [JarvusInnovations/Emergence#26]
Observed in Firefox 42.

Investigated a bit and found that the data is passing through alright but the Emergence instances isn't recognizing the data as json.

**Comment by themightychris** [comment]
@hparadiz closing because it works now? I can't recall if I ever fixed this... I might have, or maybe it just sorted itself out? IIRC it was firefox doing something weird with Accept headers

**Comment by hparadiz** [comment]
I mean it's a very old bug and I think it was fixed yea. And yea it was some weirdness with ext stores and firefox headers.
